name: Pipeline Seguro - DevSecOps

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DATABASE_USER: ${{ secrets.DATABASE_USER }}
      DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
      API_TOKEN: ${{ secrets.API_TOKEN }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Validar injeção de ambiente
        run: |
          if [ -z "${DATABASE_PASSWORD}" ]; then
            echo "[-] FALHA: Segredos não mapeados. Abortando."
            exit 1
          fi

      - name: Executar Aplicação Securizada
        run: python app/main.py

      # --- NOVO HARDENING APLICADO: BUILD E SCAN ---
      - name: Build da Imagem Docker local
        run: docker build -t devsecops-secrets-lab:latest .

      - name: Escaneamento de Vulnerabilidades (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-secrets-lab:latest'
          format: 'table'
          exit-code: '1' # Falha a esteira se achar falha crítica
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
